### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by ViliqnVachev** [luchob/softuni-sept-2021-misc#106]
Здравейте,
опитвам се да си билдна проекта, но като дам mvn clean install ми гърмят интегрейшън тестовете. Локално като пускам всички тестове минават без проблем ( не ги пускам тест по тест, а ги стартирам всички накуп). Някакви идей как може да се оправи това
 https://github.com/ViliqnVachev/movie-library

**Comment by luchob** [comment]
Хей, привет!

Вчера бях по горите, затова не писах. При мен гърми и локално:

```
java.lang.IllegalArgumentException: Illegal character in path at index 33: https://api.cloudinary.com/v1_1/${CLOUD_NAME}/image/destroy

	at java.base/java.net.URI.create(URI.java:906)
	at org.apache.http.client.methods.HttpPost.<init>(HttpPost.java:73)
	at com.cloudinary.Uploader.callApi(Uploader.java:283)
	at com.cloudinary.Uploader.destroy(Uploader.java:127)
	at com.vvachev.movielibrary.service.impl.CloudinaryServiceImpl.delete(CloudinaryServiceImpl.java:51)
	at com.vvachev.movielibrary.web.MovieControllerTest.testAddMovie(MovieControllerTest.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
```

Проблемът е очевиден, а имено че теста се опитва да вземе истинският клаудинари сървис и да качи картинката съвсем наистина. Резултатът е ясен, както се вижда от ексепшъна.

Как може да се оправи? Най-простият и образователен начин е като направиш mock на клаудинари сървиса. На първо четене, изглежда объркващо - как хем интегрейшън тест, хем mock. Всъщност е много лесно, за целта може да използваш анотацията `MockBean` по подобен начин:

```
	@MockBean
	ICloudinaryService mockCloudinaryService;
```
 
Хвърли едно очо в гугъл за тази анотация допълнително. 

Поздрави,
Л.
