### ISSUE TITLE
Проблем с UnitTest

### ISSUE THREAD

**Issue by Bozhidarov8609** [luchob/softuni-sept-2021-misc#108]
Здравей отново,
имам проблем с тестовете. Когато пусна теста ми излиза грешка, предполагам, че нещо съм пропуснал да направя като настройка за Csrf, но ако помогнеш ще съм благодарен.

https://github.com/Bozhidarov8609/Mucuna2021Final-master

java.lang.IllegalArgumentException: The HttpServletRequest attribute must contain an HttpServletResponse for the attribute javax.servlet.http.HttpServletResponse

	at org.springframework.security.web.csrf.LazyCsrfTokenRepository.getResponse(LazyCsrfTokenRepository.java:92)
	at org.springframework.security.web.csrf.LazyCsrfTokenRepository.wrap(LazyCsrfTokenRepository.java:84)
	at org.springframework.security.web.csrf.LazyCsrfTokenRepository.generateToken(LazyCsrfTokenRepository.java:58)
	at org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors$CsrfRequestPostProcessor.postProcessRequest(SecurityMockMvcRequestPostProcessors.java:236)
	at org.springframework.test.web.servlet.request.MockHttpServletRequestBuilder.postProcessRequest(MockHttpServletRequestBuilder.java:831)
	at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:173)

**Comment by luchob** [comment]
Привет!

Имам много силно предположение, че причината за този и вероятно други проблеми са в подобни депендънсита с които е осеян pom.xml:

```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
            <version>2.3.9.RELEASE</version>
        </dependency>
```

Тези версии се управляват от спринг мейвън плъгина, които пък му се задават от спринг тийма. 
Защото ти няма начин как да кажеш, че версия X на библиотека Y работи добре с версия Z на библиотека P. Депендънситата са стотици и когато добавиш грешни версии (което е 100% станало в твоя случай) програмата започва да се държи "странно" и се сипят най-невероятни и много тънки проблеми.

Опитай да изчистиш всички версии на org.springframework. След това махни junit, mockito и т.н. тъй като те идват от test стартера на спринг. След това се разходи още веднъж и махни библиотеките, които не ти трябват.

Накрая съм уверен, че проблемите ще са различни :-) и разрешими.

**Comment by Bozhidarov8609** [comment]
СУПЕР СИ. Мислих, че е добре да пъхаш яко депендънсита, а то колко изгубени часове ;)
